Vagrant.configure("2") do |config|
  config.vbguest.iso_path = "https://download.virtualbox.org/virtualbox/7.0.6/VBoxGuestAdditions_7.0.6.iso"
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "ubuntu-dc-x2"
  config.vm.network "private_network", ip: "172.16.1.12"
  config.vm.synced_folder "../data", "/home/vagrant/data"
  config.vm.provision "file", source: "copiedfile.txt", destination: "/home/vagrant/copiedfile.txt"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-dc-x2"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
